# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderModel', '0002_spider_param'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('isAlive', models.IntegerField()),
            ],
        ),
    ]
