# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderModel', '0003_ipproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipproxy',
            name='fromUser',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='addIp',
            field=models.IntegerField(default=0),
        ),
    ]
