# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderModel', '0004_auto_20170519_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='isProxy',
            field=models.IntegerField(default=0),
        ),
    ]
